name: Publish RF-DETR Pre-Releases to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+[0-9]+a[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+[0-9]+b[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+[0-9]+rc[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+a[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+b[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+rc[0-9]"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]"
  workflow_dispatch:

permissions: {} # Explicitly remove all permissions by default

jobs:
  build-pkg:
    uses: ./.github/workflows/build-package.yml

  publish-pre-release:
    name: Publish Pre-release Package
    needs: build-pkg
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://pypi.org/project/rfdetr/
    timeout-minutes: 10
    permissions:
      id-token: write # Required for PyPI publishing
    steps:
      - name: ðŸ“¥ Download distribution artifacts
        uses: actions/download-artifact@0123456789abcdef0123456789abcdef01234567 # v4
        with:
          name: dist
          path: dist/

      - name: ðŸš€ Publish to PyPi
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          attestations: true