name: Publish RF-DETR Releases to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]"
      - "[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    paths:
      - '.github/workflows/build-package.yml'
      - '.github/workflows/publish-release.yml'

permissions: {} # Explicitly remove all permissions by default

jobs:
  build-pkg:
    uses: ./.github/workflows/build-package.yml

  publish-release:
    name: Publish Release Package
    needs: build-pkg
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/rfdetr/
    timeout-minutes: 10
    permissions:
      id-token: write # Required for PyPI publishing
    steps:
      - name: ðŸ“¥ Download distribution artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v4
        with:
          name: dist
          path: dist/

      - name: ðŸš€ Publish to PyPi
        if: github.event_name != 'pull_request'
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          attestations: true
